import type { IconName } from "@/components/brand/icons";

/**
 * The team's visit to Robotex & NDTX Expo 2026 (from the organisers' brochure, expo.ndtcorner.com).
 * Applications go through the website form "robotex-2026", managed in the BuildX App → الفورمات.
 */
export const EXPO_FORM = "robotex-2026";
export const EXPO_SITE = "https://expo.ndtcorner.com";

const ar = {
  meta: { title: "زيارة معرض Robotex 2026", description: "BuildX HUE رايح زيارة لمعرض Robotex & NDTX 2026 للروبوتات والذكاء الاصطناعي والأتمتة الصناعية، 14–16 نوفمبر في مركز مصر للمعارض الدولية. قدّم من هنا." },
  eyebrow: "زيارة BuildX HUE",
  title: "Robotex & NDTX Expo 2026",
  body: "رايحين مع بعض لأول نسخة من معرض الروبوتات والذكاء الاصطناعي الصناعي في أفريقيا، جنب معرض NDTX للفحص والجودة. قدّم، واستنى القبول، وإحنا نرتّب الباقي.",
  apply: "قدّم على الزيارة",
  track: "تابع طلبك",
  facts: [
    { k: "14–16", t: "نوفمبر 2026", d: "المواعيد" },
    { k: "EIEC", t: "القاهرة الجديدة", d: "مركز مصر للمعارض الدولية" },
    { k: "+100", t: "عارض", d: "في نسخة 2025 من NDTX" },
    { k: "+7,000", t: "زائر", d: "في نسخة 2025" },
  ],
  aboutEyebrow: "عن المعرض",
  aboutTitle: "معرضين في مكان واحد",
  about: [
    { name: "ROBOTEX 26", tag: "النسخة الأولى", body: "معرض ومؤتمر دولي لتكنولوجيا الروبوتات والذكاء الاصطناعي والأنظمة الذكية وحلول المصانع الحديثة: أذرع روبوتية وروبوتات تعاونية، رؤية الآلة، الطائرات المسيرة، والتحول الرقمي." },
    { name: "NDTX 26", tag: "النسخة التالتة", body: "أكبر معرض في أفريقيا والشرق الأوسط للفحص غير الإتلافي (NDT) واللحام والتفتيش الهندسي والجودة والتآكل وتكامل الأصول، بحضور شركات ومتخصصين من البترول والطاقة والطيران والإنشاءات." },
  ],
  seeEyebrow: "هتشوف إيه",
  seeTitle: "أهم مجالات المعرض",
  see: [
    { icon: "robot", t: "الروبوتات الصناعية", b: "أذرع روبوتية، روبوتات تعاونية، أنظمة ذاتية التشغيل وتطبيقاتها." },
    { icon: "ai", t: "الذكاء الاصطناعي ورؤية الآلة", b: "الفحص بالذكاء الاصطناعي، تحليل الصور والقرارات الذكية." },
    { icon: "autonomous", t: "الطائرات المسيرة والأنظمة الذاتية", b: "طائرات صناعية وتشغيل عن بُعد وحلول ذاتية للبيئات الصناعية." },
    { icon: "sensor", t: "الفحص الروبوتي", b: "الفحص غير الإتلافي الآلي والمسح الروبوتي ومنصات الفحص المتقدمة." },
    { icon: "gauge", t: "الجودة والقياس والمعايرة", b: "رؤية الآلة وأنظمة الجودة الآلية." },
    { icon: "cpu", t: "التحول الرقمي والمصانع الذكية", b: "تحليل البيانات والحلول الرقمية لإدارة الأصول." },
  ] as { icon: IconName; t: string; b: string }[],
  stepsEyebrow: "الزيارة ماشية إزاي",
  stepsTitle: "4 خطوات وتبقى في المعرض",
  steps: [
    { t: "قدّم", b: "املأ الفورم تحت. هيظهرلك كود طلب، احتفظ بيه." },
    { t: "الفريق بيراجع", b: "بنراجع الطلبات ونبعتلك على واتساب أول ما تتقبل." },
    { t: "اتسجّلت علطول", b: "أول ما تتقبل بتبقى في وفد BuildX HUE برقم (BX-001…)، وإحنا بنبعت كشف الوفد لإدارة المعرض. مش محتاج تسجّل في أي موقع." },
    { t: "يوم الزيارة", b: "تصريحك في «تابع طلبك» (خد سكرين شوت)، وميعاد ومكان التجمع بيوصلوك على واتساب." },
  ],
  applyEyebrow: "التقديم",
  applyTitle: "قدّم على الزيارة",
  statusEyebrow: "تابع طلبك",
  statusTitle: "اعرف حالة طلبك",
  statusBody: "اكتب كود الطلب ورقم الموبايل اللي قدّمت بيه. لو اتقبلت هيظهرلك تصريح الوفد برقمك ويومك.",
  faqEyebrow: "أسئلة",
  faqTitle: "قبل ما تقدّم",
  faq: [
    { q: "الزيارة لمين؟", a: "لطلاب BuildX HUE وأي طالب مهتم بالروبوتات والذكاء الاصطناعي والهندسة. الأولوية لطلاب الفريق." },
    { q: "لازم أسجّل في موقع المعرض؟", a: "لأ. إحنا بنسجّلك ضمن وفد BuildX HUE وبنبعت الكشف لإدارة المعرض. اكتب اسمك بالإنجليزي صح في الفورم عشان يطلع كده في الكشف." },
    { q: "أقدر أروح لوحدي؟", a: "أيوه، اختار «هوصل المعرض لوحدي» في الفورم، وقابلنا هناك في الميعاد اللي هنبعته." },
    { q: "نسيت كود الطلب", a: "قدّم تاني بنفس رقم الموبايل، وهيظهرلك نفس الكود." },
  ],
  official: "موقع المعرض الرسمي",
  seeImages: ["robots", "vision", "drones", "inspection", "quality", "factory"],
  brochure: "حمّل بروشور المعرض (PDF)",
  nav: [["#about", "المعرض"], ["#areas", "المجالات"], ["#apply", "قدّم"], ["#status", "تابع طلبك"], ["#day", "يوم الزيارة"], ["#photos", "الصور"], ["#faq", "أسئلة"]] as [string, string][],
  countdown: { title: "فاضل على المعرض", d: "يوم", h: "ساعة", m: "دقيقة", s: "ثانية", live: "المعرض شغال دلوقتي 🎉", over: "المعرض خلص، شوف صور الزيارة تحت 📸" },
  barDays: { zero: "المعرض النهارده!", one: "فاضل يوم واحد", two: "فاضل يومين", few: "فاضل {n} أيام", many: "فاضل {n} يوم" },
  lightbox: { close: "قفل", prev: "اللي قبلها", next: "اللي بعدها" },
  pastEyebrow: "من المعرض",
  pastTitle: "صور من النسخ اللي فاتت",
  pastBody: "NDTX اتعمل قبل كده في نفس المكان، ودي لقطات من البروشور الرسمي للمعرض: الأجنحة، الأجهزة، المحاضرات والزوار.",
  crewEyebrow: "الوفد",
  crewTitle: "مين رايح معانا",
  crewBody: "العدد بيتحدّث أول ما الفريق يقبل حد.",
  crewGoing: "في الوفد لحد دلوقتي",
  crewLeft: "فاضل {n} مكان",
  crewFull: "الوفد كامل",
  crewClosed: "العدد هيظهر هنا أول ما القبول يبدأ.",
  planEyebrow: "يوم الزيارة",
  planTitle: "اليوم هيمشي إزاي",
  planNote: "المواعيد بالظبط بتوصلك على واتساب وفي تصريحك.",
  plan: [
    { t: "التجمع", b: "نتقابل في مكان التجمع، ونطابق الأسامي على كشف الوفد.", icon: "users" },
    { t: "على المعرض", b: "اللي جاي مع الفريق بيتحرك معانا، واللي جاي لوحده يقابلنا عند البوابة.", icon: "rocket" },
    { t: "جولة في الصالات", b: "نلف على ستاندات الروبوتات والذكاء الاصطناعي والفحص، ونسأل ونتعلم.", icon: "robot" },
    { t: "مع الشركات", b: "نتكلم مع الشركات عن التدريب والشغل، وخد معاك سؤالين جاهزين.", icon: "handshake" },
    { t: "صورة الوفد", b: "صورة جماعية لوفد BuildX HUE، وبتنزل في ألبوم الزيارة هنا.", icon: "image" },
  ] as { t: string; b: string; icon: IconName }[],
  bringTitle: "خد معاك",
  bring: ["البطاقة أو كارنيه الجامعة", "تصريح الوفد (سكرين شوت)", "موبايل مشحون + باور بانك", "مية ولبس مريح", "نوتة وقلم لأسئلتك"],
  albumEyebrow: "الصور",
  albumTitle: "ألبوم الزيارة",
  albumEmpty: "صور الوفد من المعرض هتنزل هنا بعد الزيارة 📸",
  passTitle: "تصريح وفد BuildX HUE",
  passNo: "رقمك في الوفد",
  passDay: "يومك",
  passShot: "خد سكرين شوت للتصريح وخليه معاك يوم الزيارة.",
};

const en: typeof ar = {
  meta: { title: "Robotex 2026 expo visit", description: "BuildX HUE is visiting Robotex & NDTX Expo 2026 (industrial robotics, AI and automation), 14–16 November at the Egypt International Exhibition Center. Apply here." },
  eyebrow: "A BuildX HUE visit",
  title: "Robotex & NDTX Expo 2026",
  body: "We're going together to the first edition of Africa's industrial robotics and AI expo, next to NDTX, the testing and quality expo. Apply, wait for your acceptance, and we'll arrange the rest.",
  apply: "Apply for the visit",
  track: "Check your application",
  facts: [
    { k: "14–16", t: "November 2026", d: "Dates" },
    { k: "EIEC", t: "New Cairo", d: "Egypt International Exhibition Center" },
    { k: "100+", t: "exhibitors", d: "at NDTX 2025" },
    { k: "7,000+", t: "visitors", d: "in 2025" },
  ],
  aboutEyebrow: "The expo",
  aboutTitle: "Two expos in one place",
  about: [
    { name: "ROBOTEX 26", tag: "1st edition", body: "An international expo and conference on robotics, AI, smart systems and modern factories: robot arms and cobots, machine vision, drones and digital transformation." },
    { name: "NDTX 26", tag: "3rd edition", body: "The largest expo in Africa and the Middle East for non-destructive testing, welding, engineering inspection, quality, corrosion and asset integrity, with companies and experts from oil and gas, power, aviation and construction." },
  ],
  seeEyebrow: "What you'll see",
  seeTitle: "The expo's main areas",
  see: [
    { icon: "robot", t: "Industrial robots", b: "Robot arms, cobots, autonomous systems and their applications." },
    { icon: "ai", t: "AI and machine vision", b: "AI inspection, image analysis and smart decisions." },
    { icon: "autonomous", t: "Drones and autonomous systems", b: "Industrial drones, remote operation and autonomous solutions." },
    { icon: "sensor", t: "Robotic inspection", b: "Automated NDT, robotic scanning and advanced inspection platforms." },
    { icon: "gauge", t: "Quality, measurement and calibration", b: "Machine vision and automated quality systems." },
    { icon: "cpu", t: "Digital transformation and smart factories", b: "Data analysis and digital asset management." },
  ],
  stepsEyebrow: "How the visit works",
  stepsTitle: "Four steps to the expo",
  steps: [
    { t: "Apply", b: "Fill in the form below. You'll get a reference code; keep it." },
    { t: "The team reviews", b: "We review applications and message you on WhatsApp once you're accepted." },
    { t: "You're registered", b: "Once accepted you're in the BuildX HUE delegation with a number (BX-001…), and we send the delegation list to the expo's administration. No registration on any site." },
    { t: "Visit day", b: "Your pass is under “Check your application” (take a screenshot); the meeting time and place come on WhatsApp." },
  ],
  applyEyebrow: "Apply",
  applyTitle: "Apply for the visit",
  statusEyebrow: "Check your application",
  statusTitle: "Your application status",
  statusBody: "Enter your reference code and the mobile number you applied with. Once accepted, your delegation pass with your number and day shows here.",
  faqEyebrow: "Questions",
  faqTitle: "Before you apply",
  faq: [
    { q: "Who is the visit for?", a: "BuildX HUE students and any student interested in robotics, AI and engineering. Team students come first." },
    { q: "Do I register on the expo's site?", a: "No. We register you in the BuildX HUE delegation and send the list to the expo's administration. Write your English name correctly in the form so it shows that way on the list." },
    { q: "Can I go on my own?", a: "Yes, choose “I'll get to the expo myself” in the form and meet us there at the time we send." },
    { q: "I lost my reference code", a: "Apply again with the same mobile number and you'll see the same code." },
  ],
  official: "Official expo website",
  seeImages: ["robots", "vision", "drones", "inspection", "quality", "factory"],
  brochure: "Download the expo brochure (PDF)",
  nav: [["#about", "The expo"], ["#areas", "Areas"], ["#apply", "Apply"], ["#status", "Your status"], ["#day", "Visit day"], ["#photos", "Photos"], ["#faq", "FAQ"]],
  countdown: { title: "Until the expo", d: "days", h: "hours", m: "min", s: "sec", live: "The expo is on now 🎉", over: "The expo is over; see the visit's photos below 📸" },
  barDays: { zero: "The expo is today!", one: "1 day to go", two: "2 days to go", few: "{n} days to go", many: "{n} days to go" },
  lightbox: { close: "Close", prev: "Previous", next: "Next" },
  pastEyebrow: "From the expo",
  pastTitle: "Photos from past editions",
  pastBody: "NDTX has been held at the same venue before. These shots are from the expo's official brochure: the stands, the equipment, the talks and the visitors.",
  crewEyebrow: "The delegation",
  crewTitle: "Who's coming with us",
  crewBody: "The count updates as soon as the team accepts someone.",
  crewGoing: "in the delegation so far",
  crewLeft: "{n} places left",
  crewFull: "The delegation is full",
  crewClosed: "The count shows here once acceptances start.",
  planEyebrow: "Visit day",
  planTitle: "How the day goes",
  planNote: "Exact times come on WhatsApp and on your pass.",
  plan: [
    { t: "Meet up", b: "We meet at the meeting point and check names against the delegation list.", icon: "users" },
    { t: "To the expo", b: "If you're coming with the team you travel with us; otherwise meet us at the gate.", icon: "rocket" },
    { t: "Tour the halls", b: "We go round the robotics, AI and inspection stands, ask questions and learn.", icon: "robot" },
    { t: "Meet companies", b: "We talk to companies about internships and jobs. Bring two questions ready.", icon: "handshake" },
    { t: "Delegation photo", b: "A group photo of the BuildX HUE delegation, posted to the visit album here.", icon: "image" },
  ],
  bringTitle: "Bring with you",
  bring: ["Your ID or university card", "Your delegation pass (screenshot)", "A charged phone + power bank", "Water and comfortable clothes", "A notebook for your questions"],
  albumEyebrow: "Photos",
  albumTitle: "Visit album",
  albumEmpty: "The delegation's photos from the expo go up here after the visit 📸",
  passTitle: "BuildX HUE delegation pass",
  passNo: "Your delegation number",
  passDay: "Your day",
  passShot: "Take a screenshot of your pass and keep it with you on the day.",
};

export const expoVisit = (locale: string) => (locale === "ar" ? ar : en);
